spring:
    application:
        name: dubbo-sample-provider
    dubbo:
        scan: samples.dubbo.service
        application:
            name: dubbo-sample-provider
        registry:
            address: zookeeper://192.168.150.129:2181
        protocol:
            name: dubbo
            port: 20880
---
server:
    servlet-path: /
    port: 8081